### ISSUE TITLE
Replace / in cloudWatchRule name

### ISSUE THREAD

**Issue by milancermak** [AlexanderMS/serverless-plugin-existing-cloudwatch-rule#1]
Hi,

first of all, thank you for this plugin, it's very handy, something I expected SLS would support out of the box. I tried to use it in my project, but ran into an issue with the name of the rule I use.

My rule's name was autogenerated by Cloudformation, when it created the stack, so it's something like `rule/my-project-PostPDTMidnightSchedule-23RFYATBBVIET`. The plugin then generates an invalid CFN resource name because of the `/` in my rule.

I managed to work around it by just simply removing the slash from the name. If you think that's a good solution, I could send a PR.

**Comment by alex-murashkin** [comment]
Ah right, I see what's going on! Absolutely, feel free to send a PR, and I will approve it.
