### ISSUE TITLE
Support full ARNs

### ISSUE THREAD

**Issue by milancermak** [AlexanderMS/serverless-plugin-existing-cloudwatch-rule#2]
When I used this plugin the first time, I assumed it will accept a complete ARN, as that's what goes into the `SourceArn` in the `AWS::Lambda::Permission` resource. However that's not the case.

What do you think about adding this functionality? 

I was thinking it could be under a separate name in the `events` section, say `cloudWatchRuleARN`, so the change is backwards compatible. If you agree, I could send a PR for this too.

**Comment by alex-murashkin** [comment]
Sounds like a good feature. You're welcome to send a PR! 👍 
re: name: `cloudWatchRuleArn` vs `cloudWatchRuleARN`? not sure what's more common in other serverless plugins, but could go either way :)

**Comment by milancermak** [comment]
You're right, `Arn` seems like a better fit, also CFN uses it.
